# Generated by Django 3.0.4 on 2020-04-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentStats',
            fields=[
                ('letter', models.CharField(max_length=1, primary_key=True, serialize=False)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('correct', models.IntegerField()),
                ('wrong', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OverallStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('speed', models.DecimalField(decimal_places=2, max_digits=4)),
                ('accuracy', models.DecimalField(decimal_places=2, max_digits=4)),
                ('duration', models.IntegerField()),
            ],
        ),
    ]
